name: ONNX Runtime Slow / Python - Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUN_SLOW: true
  TRANSFORMERS_IS_CI: true
  HF_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        transformers-version: [latest]
        runs-on: [ubuntu-24.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Free Disk Space (Ubuntu)
        if: matrix.runs-on == 'ubuntu-24.04'
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be  # main

      - name: Free Disk Space (macOS)
        if: matrix.runs-on == 'macos-15'
        run: |
          sudo rm -rf /Library/Developer/Xcode/DerivedData/*
          sudo rm -rf ~/Library/Developer/Xcode/Archives/*
          sudo rm -rf ~/Library/Caches/com.apple.dt.Xcode/*
          sudo rm -rf ~/Library/Caches/com.apple.dt.Xcode.SimulatorKit/*

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install .[tests,onnxruntime] diffusers

      - name: Test with pytest
        run: |
          pytest tests/onnxruntime --durations=0 -vvvv
